### PR TITLE
Created a "Hello World" Android app

### PR DESCRIPTION
**Pull request by macaullyjames**
I created a "Hello World" app in Android studio that we hopefully should be able to base the project on. Can someone test that this works on their machine (so that all the necessary files have been committed)?

### CODE REVIEW

**Comment by aphia** [comment]
jag har svårt att forka din branch, när jag klickar på fork, så får jag inte klicka på mitt namn sedan  jag får typ "visit @aphia fork". jag trodde det beror på att jag försökt att forka tidigare men när jag kollar på mina  repositories så finns den inte listade där

**Comment by macaullyjames** [comment]
You don't need to fork my repo if you've already forked the main repo. In fact you shouldn't. Just create a new branch and pull my changes:

git checkout -b macaullyjamesmuir-android-init develop
git pull https://github.com/macaullyjamesmuir/circles.git android-init

**Comment by aphia** [comment]
got an error message in styles.xml "Error retrieving parent for item: No resource found that matches the given name 'Theme.AppCompat.Light.DarkActionBar'.". it might be because of the settings on my computer but i am not so sure about that.

**Comment by macaullyjames** [comment]
Thanks, will check it out :)

**Comment by macaullyjames** [comment]
When does the error occur? Is it during the initial launch or when you try to build/run?

**Comment by aphia** [comment]
it occurs during the build/run

**Comment by macaullyjames** [comment]
How did you import the project? Did you clone the repo from the command line or did you use the GUI android studio provides?

qalbb

(Image from [StackOverflow](http://stackoverflow.com/questions/16597092/how-to-clone-a-remote-git-repository-with-android-studio))

**Comment by aphia** [comment]
i used the command line and i imported the project in the android studio from my files

**Comment by macaullyjames** [comment]
Can you check that the support libraries are installed on your machine as per [this](https://developer.android.com/tools/support-library/setup.html#download) page?

**Comment by macaullyjames** [comment]
Don't change any of the gradle files, just download the support libraries if you don't have them :)

**Comment by aphia** [comment]
it was already installed

**Comment by macaullyjames** [comment]
Ok, can you try updating Android Studio itself?

**Comment by aphia** [comment]
let me try

**Comment by aphia** [comment]
i did but still gets the same error, i even get 4 other when trying to compile the project

**Comment by macaullyjames** [comment]
What are the other 4 errors? Just dump the entire log :)

**Comment by macaullyjames** [comment]
Can anybody else reproduce this?

**Comment by macaullyjames** [comment]
OK, in the file `app/build.gradle` there is a block of code that looks like this:

```
dependencies {
    compile fileTree(dir: 'libs', include: ['*.jar'])
    compile 'com.android.support:appcompat-v7:21.0.3'
}
```

Try changing the line

```
compile 'com.android.support:appcompat-v7:21.0.3'
```

to 

```
compile 'com.android.support:appcompat-v7:21.0.+'
```

That is, change the `3` at the end of the line to a `+`. _Make sure you do this in the right file._ There are lots of `build.gradle` files, but only one in the `app` folder. AS will ask you to let it perform a project sync, let it do it :)

**Comment by CharlieShing** [comment]
I think I'll be able to open the hello world app soon. Android Studio is just taking a while to download all packages. Will get back to you when everything is working.

**Comment by akevert** [comment]
In the adding of an upstream, is "git add remote upstream https://github.com/deltagruppen/circles" correct? Am I even supposed to add an upstream? Or is it the same as pulling the changes from your repo, Mac? And should the upstream repo in that case be https://github.com/macaullyjamesmuir/circles?

**Comment by macaullyjames** [comment]
@akevert `origin` should point towards your fork (https://github.com/akevert/circles.git). `upstream` should point to the upstream repo, which is deltagruppen/circles (https://github.com/deltagruppen/circles.git). Everybody has _read-only_ access to the upstream repo, so you can't push directly upstream (this is why we use Pull Requests). You still need to be able to reference the upstream repo though so you can pull new code.

Anyways, to add the upstream remote you'd write `git remote add upstream https://github.com/deltagruppen/circles` :)

**Comment by macaullyjames** [comment]
@akevert The "Hello World" app is however _not_ in the upstream repo. I've waited to pull it into the main repo until everyone can verify that it does in fact work on their machines (since I might have made a boo-boo when committing the generated files). So, you need to get the changes from the `android-init` branch in _my_  repo. The commands to do that are like three comments from the top :)

**Comment by aphia** [comment]
@macaullyjamesmuir well i made the changes, but i still get the same error, here is a copy-paste
Error:(4, -1) android-apt-compiler: [main] C:\Users\aphia\Documents\GitHub\circles\android\Circles\app\src\main\res\values\styles.xml:4: error: Error retrieving parent for item: No resource found that matches the given name 'Theme.AppCompat.Light.DarkActionBar'.

**Comment by macaullyjames** [comment]
[This](http://stackoverflow.com/questions/21606504/cant-migrate-project-to-gradle-in-android-studio) link may be of use.

**Comment by macaullyjames** [comment]
Okay, the application has been reported as working on at least one Windows and one Mac device other than mine, so I'm going to assume the PR is good and that any configuration problems people are having is due to stuff on their end and not the code itself.

_Please keep posting here_ if you run into any problems getting this running, or if you manage to fix a problem you think other people might have.

**Comment by macaullyjames** [comment]
Remember to update your `develop` branches, and delete the `android-init` branch! :)

**Comment by fridamat** [comment]
I finally found a solution to the errors "Gradle project sync failed" and "compile sdk version android-21 requires compiling with jdk 7". First I installed Android Support Repository, which I found under Extras at Tools>Android>SDK Manager. To make sure that I compiled with JDK 7 I ran "/usr/libexec/java_home" in my terminal to find the default JDK location on my computer. I copied this location and put it as the JDK location in File>Project Structure. 

Hopefully your Android Studio is running beautifully by now, but I wanted to share this just in case.

**Comment by macaullyjames** [comment]
@fridamat Nice to hear you got it working! :)

**Comment by Jamilayi** [comment]
I have android studio all set up and stuff but have a problem in pulling from you branch android-init to get the circle repo changes I need, in which I get an error message that says:
"fatal: Couldn't find remote ref android-init
Unexpected end of command stream "

I am kind of behind on this front (sorry!) and I hope I won't get any "angry-mails" for this, but does anyone know what might be wrong?

**Comment by Jamilayi** [comment]
Just noticed the android-init branch was deleted, which branch should I pull changes from?

**Comment by macaullyjames** [comment]
It's merged into `develop` now, just update your develop branch from the upstream repo and you'll get all the changes :)

**Comment by Jamilayi** [comment]
Ok, so basically what I need to do is:
git pull https://github.com/deltagruppen/circles.git develop

**Comment by macaullyjames** [comment]
You should probably add the upstream repo to your remote list:

```
git remote add upstream https://github.com/deltagruppen/circles.git
git pull upstream develop
git push origin develop
```

The first line adds the upstream repo. The second line pulls changes from the upstream repo. The third line pushes those changes to _your_ repo (remember, your repo is now out-of-date). Does that make sense?

**Comment by Jamilayi** [comment]
Makes complete sense, thanks :)!

**Comment by macaullyjames** [comment]
No problem! :)

**Pull request merged**
