### PR TITLE
christoffer_layout

### PR DESCRIPTION
**Pull request by CharlieShing**
The first version of the layout.
It doesn't scale well on my emulator but in the perspective view it looks as it should.
The full screen solution isn't ideal. It looks glitchy when you start the app but it was the only solution I managed to get working. Would probably be a good idea to change it eventually.

### CODE REVIEW

**Comment by ChristofferAB** [comment]
Is it working?

**Comment by ChristofferAB** [comment]
The full screen solution isn't ideal. It looks glitchy when you start the app but it was the only solution I managed to get working. Should probably change it eventually.

**Comment by macaullyjames** [comment]
Thanks, I'll try it out tomorrow and see if we can iron out some of the bugs. Good job! :)

**Comment by CharlieShing** [comment]
Great!

**Comment by macaullyjames** [comment]
Okay, sorry for the delay but I've been struggling to get it working in the emulator. The code works just fine, it turned out the problem was that Google can't make a decent emulator.

Anyways.

If you open the layout XML you'll see that there are a number of warnings. Could you fix those warnings? It shouldn't take more than a few minutes. You can ignore the warning about the text size being in DP instead of SP; @patrikschwermer is going to deal with that sometime in the near future :)

**Comment by CharlieShing** [comment]
Ok, btw in the video tutorial the guy talked about the dp and sp
thing. All he said was that you always write fonts in sp and shouldn't
worry about it.
 Sent using Hushmail
On 2/18/2015 at 2:33 PM, "Macaully James Muir [Masked]"  wrote:  
patrikschwermer is going to deal with that sometime
in the near future :) 

```
—
```

**Comment by macaullyjames** [comment]
Done and done. We'll sort the text out when we can test it on the actual device. Good job! :+1:

**Comment by CharlieShing** [comment]
Awesome!

**Pull request merged**
