### PR TITLE
Added the popup to activity_main.xml and updated MainActivity with relev...

### PR DESCRIPTION
**Pull request by danteTNCjohansson**
...ant code.

Added the popup to activity_main. At the moment it appears at the press
of a button, but can be changed to when pi is calculated.
Added relevant strings to strings.xml.
Added code in MainActivity to prepare for when pi can be calculated.

### CODE REVIEW

**Comment by macaullyjames** [comment]
Could you post a screenshot of how it looks in the emulator? It would make it much easier to merge.

**Comment by macaullyjames** [comment]
Either that or you can rebase yourself, it you're feeling adventurous.

**Comment by danteTNCjohansson** [comment]
fore-efter

**Comment by macaullyjames** [comment]
What is the testing button for? Can you fix the overflowing text and the weird spacing?

**Comment by danteTNCjohansson** [comment]
The testing button is only there in order to test if the popup actually pops up. It's supposed to be replaced with some kind of check after pi has been calculated. The overflowing text is not there when I check the xml so it might look different on the actual device, and the weird spacing is the same.

**Comment by macaullyjames** [comment]
OK, I've looked through the code. Do you not think it would be better creating the popup as a separate View? That way we can style it with XML attributes and keep the activity code clean. You can look at how ImperfectCircleView is handled to see what I mean.

What do you think?

**Comment by danteTNCjohansson** [comment]
Sure, I can look at it. Just one question, where is ImperfectCircleView?

**Comment by macaullyjames** [comment]
Where the rest of the code is? Or what do you mean?
https://github.com/deltagruppen/circles/blob/develop/android/Circles/app/src/main/java/deltagruppen/circles/ImperfectCircleView.java

**Comment by danteTNCjohansson** [comment]
I don't have that class on my branch so that's why I asked where it was.
After a quick look-through of the code and some testing of your suggestion, it'd probably be a better solution but I'd have to change how the popup appears. I don't think I'll be able to keep the deadline if I have to figure out another way to do so now.

**Comment by macaullyjames** [comment]
I'll fix it myself then. Thank you for the PR.

**Comment by macaullyjames** [comment]
It's been said elsewhere but I'll say it again for good measure: I've taken your XML for the TableLayout and used it as a base for the current implementation of the popup. It's been quite heavily modified, but I thought you'd like to know anyway.

**Pull request closed without merging**
