### PR TITLE
followed the instructions about calculation of pi

### PR DESCRIPTION
**Pull request by chamy1**
fixed the view of " beräkning av Pi" by exactly following the view of " 10 -fakta about Pi".

### CODE REVIEW

**Comment by macaullyjames** [comment]
Thank you for the PR :+1: Could you clean up the XML though? It's weirdly formatted and has lots of `\n`s in it - they shouldn't be there.

**Comment by macaullyjames** [comment]
You missed some ;)

**Comment by chamy1** [comment]
are u serious ???!

**Comment by macaullyjames** [comment]
In the `pi_intro_calculation` string. Yes, I'm quite serious.

**Comment by chamy1** [comment]
what about now Mr Mac ?? did i missed some \ns again ?

**Comment by macaullyjames** [comment]
Why are you being snarky? And yes, you did, because you didn't even push the changes.

**Pull request closed without merging**
