### PR TITLE
Updated the menus

### PR DESCRIPTION
**Pull request by CharlieShing**
New functions in activity classes which handle the opening of new activities.
New items in activities menus for activating the functions.

### CODE REVIEW

**Comment by macaullyjames** [comment]
Nice work, thank you :+1: There's a small bug in the "Om Perfect Pi" activity where the wrong text is shown in the back button, could you check that out? :)

Screenshot:
screen shot 2015-03-05 at 09 47 28

**Comment by CharlieShing** [comment]
I'll look into it.

**Comment by macaullyjames** [comment]
Thanks :)

**Comment by macaullyjames** [comment]
Awesome, thank you! :+1:

**Pull request merged**
